## _Single Perceptron_

### _In this article we will go through a single-layer perceptron this is the first and basic model of the artificial neural networks. It is also called the feed-forward neural network. The working of the single-layer perceptron (SLP) is based on the threshold transfer between the nodes. This is the simplest form of ANN and it is generally used in the linearly based cases for the machine learning problems._

## _Working of Single Layer Perceptron_

### _The SLP looks like the below_
![](https://cdn.educba.com/academy/wp-content/uploads/2020/02/Single-Layer-Perceptron-01.jpg.webp)

### _Let’s understand the algorithms behind the working of Single Layer Perceptron:_
 *  _In a single layer perceptron, the weights to each input node are assigned randomly since there is no a priori knowledge associated with the nodes._
 *  _Also, a threshold value is assigned randomly_
 *  _Now SLP sums all the weights which are inputted and if the sums are is above the threshold then the network is activated._
 *  _If the calculated value is matched with the desired value, then the model is successful_
 *  _lf it is not, then since there is no back-propagation technique involved in this the error needs to be calculated using the below formula and the weights need to be adjusted again._

## _Perceptron Weight Adjustment_
### _Below is the equation in Perceptron weight adjustment:_
* # _Δw = η * d * x_
### Where,

*  d: Predicted Output – Desired Output
*  η: Learning Rate, Usually Less than 1.
*  x: Input Data.

### _Note: Since this network model works with the linear classification and if the data is not linearly separable, then this model will not show the proper results._

#### _Let's work on coding session to understand more deeper_
#### _Let's take a iris dataset and classify them using SLP_

In [13]:
# import required libraries
from sklearn.linear_model import Perceptron
from sklearn.datasets import load_iris

In [14]:
iris = load_iris()

In [15]:
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [16]:
X = iris.data[:,(2,3)] # we only use 2 features (petal length , petal width)

In [17]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Categories
*  0 = setosa
*  1 = veriscolor
*  2 = virginica

#### we will only classify whether it is setosa or not 

In [18]:
y = (iris.target == 0)

In [19]:
y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [20]:
import numpy as np
y =  (iris.target == 0).astype(np.int)

In [21]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Let's build a model and fead the data

In [22]:
model = Perceptron(random_state = 42)

In [23]:
model.fit(X,y)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=42, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [24]:
train_preds = model.predict(X)

In [25]:
# let's check the accuracy
from sklearn.metrics import accuracy_score
train_accuracy = accuracy_score(y,train_preds)
train_accuracy

1.0

In [27]:
# we got 100% accuracy
# now check the values of model parameters (weights and bias)
model.coef_ , model.intercept_

(array([[-1.4, -2.2]]), array([4.]))

In [ ]:
## that means our equation of model looks like
### ( -1.4x1 - 2.2x2 + 4 )